/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Admin
 */
public class DatPhong_view extends javax.swing.JInternalFrame {
       
    DatPhong_KhachHang_view datPhong_khachHang = new DatPhong_KhachHang_view();
    DatPhong_DatPhong_view datPhong_datPhong = new DatPhong_DatPhong_view(); 

    /**
     * Creates new form DatPhong
     */
    public DatPhong_view() {
        initComponents();
        
        this.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        datPhong_datPhong.setVisible(true);        
        datPhong_khachHang.setVisible(true);
        
        btn_KhachHang.setBackground(new java.awt.Color(45, 135, 186));
        
        jDesktopPane1.add(datPhong_khachHang);
        jDesktopPane1.add(datPhong_datPhong);
        

        
  // Get the title bar and set it to null
  


  //frame.setBackground(Color.white);      

  setVisible(true);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_body = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btn_KhachHang = new javax.swing.JButton();
        btn_DatPhong = new javax.swing.JButton();
        account_holder = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        footer = new javax.swing.JPanel();
        Order_btn_gr = new javax.swing.JPanel();
        btn_saoChep = new javax.swing.JButton();
        btn_CapNhat = new javax.swing.JButton();
        btn_TaoMoi = new javax.swing.JButton();
        label_maDatPhong = new javax.swing.JLabel();
        label_maHoaDon = new javax.swing.JLabel();

        main_body.setBackground(new java.awt.Color(255, 255, 255));
        main_body.setMinimumSize(new java.awt.Dimension(1643, 1643));
        main_body.setPreferredSize(new java.awt.Dimension(1643, 1080));

        header.setBackground(new java.awt.Color(190, 190, 190));
        header.setPreferredSize(new java.awt.Dimension(1643, 84));

        btn_KhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download.png"))); // NOI18N
        btn_KhachHang.setText("     KHÁCH HÀNG");
        btn_KhachHang.setBorder(null);
        btn_KhachHang.setBorderPainted(false);
        btn_KhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_KhachHang.setIconTextGap(0);
        btn_KhachHang.setMargin(new java.awt.Insets(1, 10, 3, 14));
        btn_KhachHang.setPreferredSize(new java.awt.Dimension(196, 54));
        btn_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KhachHangActionPerformed(evt);
            }
        });

        btn_DatPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_DatPhong.setForeground(new java.awt.Color(51, 51, 51));
        btn_DatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tải xuống (7) (1) (1).png"))); // NOI18N
        btn_DatPhong.setMnemonic(' ');
        btn_DatPhong.setText("     ĐẶT PHÒNG");
        btn_DatPhong.setToolTipText("");
        btn_DatPhong.setActionCommand("         Hóa đơn");
        btn_DatPhong.setBorder(null);
        btn_DatPhong.setBorderPainted(false);
        btn_DatPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_DatPhong.setMargin(new java.awt.Insets(1, 10, 3, 14));
        btn_DatPhong.setMaximumSize(new java.awt.Dimension(167, 25));
        btn_DatPhong.setMinimumSize(new java.awt.Dimension(167, 25));
        btn_DatPhong.setPreferredSize(new java.awt.Dimension(196, 54));
        btn_DatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DatPhongActionPerformed(evt);
            }
        });

        account_holder.setBackground(new java.awt.Color(217, 218, 223));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Xin chào, Dick");
        jLabel1.setToolTipText("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (2).png"))); // NOI18N

        javax.swing.GroupLayout account_holderLayout = new javax.swing.GroupLayout(account_holder);
        account_holder.setLayout(account_holderLayout);
        account_holderLayout.setHorizontalGroup(
            account_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(account_holderLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        account_holderLayout.setVerticalGroup(
            account_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(account_holderLayout.createSequentialGroup()
                .addGroup(account_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(account_holderLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(account_holderLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(190, 190, 190));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btn_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_DatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224)
                .addComponent(account_holder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(account_holder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );

        footer.setBackground(new java.awt.Color(190, 190, 190));
        footer.setPreferredSize(new java.awt.Dimension(1643, 84));

        Order_btn_gr.setBackground(new java.awt.Color(190, 190, 190));
        Order_btn_gr.setToolTipText("");

        btn_saoChep.setBackground(new java.awt.Color(45, 135, 186));
        btn_saoChep.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_saoChep.setForeground(new java.awt.Color(255, 255, 255));
        btn_saoChep.setText("Sao Chép");
        btn_saoChep.setBorder(null);
        btn_saoChep.setBorderPainted(false);
        btn_saoChep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_saoChep.setMargin(new java.awt.Insets(1, 10, 3, 14));
        btn_saoChep.setPreferredSize(new java.awt.Dimension(196, 54));
        btn_saoChep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saoChepActionPerformed(evt);
            }
        });

        btn_CapNhat.setBackground(new java.awt.Color(45, 135, 186));
        btn_CapNhat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_CapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btn_CapNhat.setText("Tạo mới");
        btn_CapNhat.setBorder(null);
        btn_CapNhat.setBorderPainted(false);
        btn_CapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_CapNhat.setMargin(new java.awt.Insets(1, 10, 3, 14));
        btn_CapNhat.setPreferredSize(new java.awt.Dimension(196, 54));
        btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatActionPerformed(evt);
            }
        });

        btn_TaoMoi.setBackground(new java.awt.Color(45, 135, 186));
        btn_TaoMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TaoMoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_TaoMoi.setText("Cập nhật");
        btn_TaoMoi.setBorder(null);
        btn_TaoMoi.setBorderPainted(false);
        btn_TaoMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_TaoMoi.setMargin(new java.awt.Insets(1, 10, 3, 14));
        btn_TaoMoi.setPreferredSize(new java.awt.Dimension(196, 54));
        btn_TaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Order_btn_grLayout = new javax.swing.GroupLayout(Order_btn_gr);
        Order_btn_gr.setLayout(Order_btn_grLayout);
        Order_btn_grLayout.setHorizontalGroup(
            Order_btn_grLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Order_btn_grLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(btn_saoChep, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_TaoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        Order_btn_grLayout.setVerticalGroup(
            Order_btn_grLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Order_btn_grLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Order_btn_grLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_saoChep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_CapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_TaoMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        label_maDatPhong.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        label_maDatPhong.setForeground(new java.awt.Color(51, 51, 255));
        label_maDatPhong.setText("Mã đặt phòng: ");

        label_maHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        label_maHoaDon.setForeground(new java.awt.Color(255, 0, 0));
        label_maHoaDon.setText("Mã hóa đơn: ");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_maDatPhong)
                    .addComponent(label_maHoaDon))
                .addGap(500, 500, 500)
                .addComponent(Order_btn_gr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addComponent(Order_btn_gr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(label_maHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_maDatPhong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout main_bodyLayout = new javax.swing.GroupLayout(main_body);
        main_body.setLayout(main_bodyLayout);
        main_bodyLayout.setHorizontalGroup(
            main_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_bodyLayout.createSequentialGroup()
                .addGroup(main_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, 1252, Short.MAX_VALUE)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 1252, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1))
                .addGap(0, 0, 0))
        );
        main_bodyLayout.setVerticalGroup(
            main_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_bodyLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(main_body, javax.swing.GroupLayout.PREFERRED_SIZE, 1252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(main_body, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KhachHangActionPerformed
        btn_KhachHang.setBackground(new java.awt.Color(45, 135, 186));
        btn_DatPhong.setBackground(new java.awt.Color(255, 255, 255));
        
        datPhong_datPhong.setVisible(false);
        datPhong_khachHang.setVisible(true);


    }//GEN-LAST:event_btn_KhachHangActionPerformed

    private void btn_DatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DatPhongActionPerformed
        // TODO add your handling code here:
        btn_DatPhong.setBackground(new java.awt.Color(45, 135, 186));
        btn_KhachHang.setBackground(new java.awt.Color(255, 255, 255));
        
        
        datPhong_khachHang.setVisible(false);
        datPhong_datPhong.setVisible(true);
    }//GEN-LAST:event_btn_DatPhongActionPerformed

    private void btn_saoChepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saoChepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_saoChepActionPerformed

    private void btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CapNhatActionPerformed

    private void btn_TaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TaoMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Order_btn_gr;
    private javax.swing.JPanel account_holder;
    private javax.swing.JButton btn_CapNhat;
    private javax.swing.JButton btn_DatPhong;
    private javax.swing.JButton btn_KhachHang;
    private javax.swing.JButton btn_TaoMoi;
    private javax.swing.JButton btn_saoChep;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_maDatPhong;
    private javax.swing.JLabel label_maHoaDon;
    private javax.swing.JPanel main_body;
    // End of variables declaration//GEN-END:variables
}
