/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;




import view.DatPhong_view;
import view.HoaDon_view;
import view.DonDatPhong_view;



import javax.swing.JFrame;

/**
 *
 * @author Admin
 */
public class LeTan_Main_view extends javax.swing.JFrame {
        DatPhong_view dp;
        DonDatPhong_view ddp;
        HoaDon_view hoaDon;
    /**
     * Creates new form NewJFrame
     */
    public LeTan_Main_view() {
        initComponents();
        
        
        btn_DatPhong.setBackground(new java.awt.Color(45, 135, 186));
        btn_DatPhong.setForeground(new java.awt.Color(0, 0, 0));
         dp  = new DatPhong_view();
         ddp = new DonDatPhong_view();
         hoaDon = new HoaDon_view();
        dp.setVisible(true);
        ddp.setVisible(true);
        hoaDon.setVisible(true);
        jDesktopPane1.add(dp); 
        jDesktopPane1.add(ddp); 
        jDesktopPane1.add(hoaDon); 
        
        
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);


        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_wrapper = new javax.swing.JPanel();
        logo_holder = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        SideBar = new javax.swing.JPanel();
        btn_DatPhong = new javax.swing.JButton();
        btn_DonDatPhong = new javax.swing.JButton();
        btn_HoaDon = new javax.swing.JButton();
        btn_DangXuat = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_wrapper.setBackground(new java.awt.Color(50, 155, 214));
        menu_wrapper.setPreferredSize(new java.awt.Dimension(277, 1090));

        logo_holder.setPreferredSize(new java.awt.Dimension(277, 84));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tải xuống (5).png"))); // NOI18N

        javax.swing.GroupLayout logo_holderLayout = new javax.swing.GroupLayout(logo_holder);
        logo_holder.setLayout(logo_holderLayout);
        logo_holderLayout.setHorizontalGroup(
            logo_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_holderLayout.createSequentialGroup()
                .addComponent(logo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        logo_holderLayout.setVerticalGroup(
            logo_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logo_holderLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBar.setBackground(new java.awt.Color(50, 155, 214));
        SideBar.setMinimumSize(new java.awt.Dimension(277, 1090));
        SideBar.setPreferredSize(new java.awt.Dimension(277, 1006));

        btn_DatPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_DatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download.png"))); // NOI18N
        btn_DatPhong.setText("    ĐẶT PHÒNG");
        btn_DatPhong.setToolTipText("");
        btn_DatPhong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));
        btn_DatPhong.setBorderPainted(false);
        btn_DatPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_DatPhong.setMargin(new java.awt.Insets(1, 10, 3, 14));
        btn_DatPhong.setPreferredSize(new java.awt.Dimension(196, 54));
        btn_DatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DatPhongActionPerformed(evt);
            }
        });

        btn_DonDatPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_DonDatPhong.setForeground(new java.awt.Color(51, 51, 51));
        btn_DonDatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tải xuống (7) (1) (1).png"))); // NOI18N
        btn_DonDatPhong.setText("  HÓA ĐƠN");
        btn_DonDatPhong.setToolTipText("");
        btn_DonDatPhong.setActionCommand("      Hóa đơn");
        btn_DonDatPhong.setBorder(null);
        btn_DonDatPhong.setBorderPainted(false);
        btn_DonDatPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_DonDatPhong.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_DonDatPhong.setMargin(new java.awt.Insets(1, 10, 3, 14));
        btn_DonDatPhong.setPreferredSize(new java.awt.Dimension(196, 54));
        btn_DonDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DonDatPhongActionPerformed(evt);
            }
        });

        btn_HoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tải xuống (6) (1).png"))); // NOI18N
        btn_HoaDon.setText("   ĐƠN ĐẶT PHÒNG");
        btn_HoaDon.setToolTipText("");
        btn_HoaDon.setBorder(null);
        btn_HoaDon.setBorderPainted(false);
        btn_HoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_HoaDon.setIconTextGap(0);
        btn_HoaDon.setMargin(new java.awt.Insets(1, 10, 3, 14));
        btn_HoaDon.setMaximumSize(new java.awt.Dimension(167, 25));
        btn_HoaDon.setMinimumSize(new java.awt.Dimension(167, 25));
        btn_HoaDon.setPreferredSize(new java.awt.Dimension(196, 54));
        btn_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HoaDonActionPerformed(evt);
            }
        });

        btn_DangXuat.setBackground(new java.awt.Color(214, 50, 50));
        btn_DangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_DangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btn_DangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (1).png"))); // NOI18N
        btn_DangXuat.setText("Đăng xuất");
        btn_DangXuat.setBorder(null);
        btn_DangXuat.setBorderPainted(false);
        btn_DangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_DangXuat.setIconTextGap(20);
        btn_DangXuat.setMargin(new java.awt.Insets(1, 10, 3, 14));
        btn_DangXuat.setPreferredSize(new java.awt.Dimension(196, 54));
        btn_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_DonDatPhong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                        .addComponent(btn_DatPhong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_HoaDon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btn_DatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_DonDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(357, 357, 357)
                .addComponent(btn_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menu_wrapperLayout = new javax.swing.GroupLayout(menu_wrapper);
        menu_wrapper.setLayout(menu_wrapperLayout);
        menu_wrapperLayout.setHorizontalGroup(
            menu_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo_holder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menu_wrapperLayout.setVerticalGroup(
            menu_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_wrapperLayout.createSequentialGroup()
                .addComponent(logo_holder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1643, 1080));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1587, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu_wrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE)
                    .addComponent(menu_wrapper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DatPhongActionPerformed
        // TODO add your handling code here:
        btn_DatPhong.setBackground(new java.awt.Color(45, 135, 186));
        btn_DatPhong.setForeground(new java.awt.Color(0, 0, 0));
        
        btn_HoaDon.setBackground(new java.awt.Color(255, 255, 255));
        btn_HoaDon.setForeground(new java.awt.Color(0, 0, 0));
        
        btn_DonDatPhong.setBackground(new java.awt.Color(255, 255, 255));
        btn_DonDatPhong.setForeground(new java.awt.Color(0, 0, 0));
        
        dp.setVisible(true);
        ddp.setVisible(false);
        hoaDon.setVisible(false);
           
        
    }//GEN-LAST:event_btn_DatPhongActionPerformed

    private void btn_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HoaDonActionPerformed
        btn_HoaDon.setBackground(new java.awt.Color(45, 135, 186));
        btn_HoaDon.setForeground(new java.awt.Color(0, 0, 0));
        
        btn_DatPhong.setBackground(new java.awt.Color(255, 255, 255));
        btn_DatPhong.setForeground(new java.awt.Color(0, 0, 0));
        
        btn_DonDatPhong.setBackground(new java.awt.Color(255, 255, 255));
        btn_DonDatPhong.setForeground(new java.awt.Color(0, 0, 0));
        
          dp.setVisible(false); 
        ddp.setVisible(false);
        hoaDon.setVisible(true);
        
     
       
        
        
    }//GEN-LAST:event_btn_HoaDonActionPerformed

    private void btn_DonDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DonDatPhongActionPerformed
        // TODO add your handling code here:
        btn_DonDatPhong.setBackground(new java.awt.Color(45, 135, 186));
        btn_DonDatPhong.setForeground(new java.awt.Color(0, 0, 0));
        
        btn_DatPhong.setBackground(new java.awt.Color(255, 255, 255));
        btn_DatPhong.setForeground(new java.awt.Color(0, 0, 0));
        
        btn_HoaDon.setBackground(new java.awt.Color(255, 255, 255));
        btn_HoaDon.setForeground(new java.awt.Color(0, 0, 0));
        
       
        
         dp.setVisible(false);
        ddp.setVisible(true);
        hoaDon.setVisible(false);
    }//GEN-LAST:event_btn_DonDatPhongActionPerformed

    private void btn_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeTan_Main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeTan_Main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeTan_Main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeTan_Main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeTan_Main_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SideBar;
    private javax.swing.JButton btn_DangXuat;
    private javax.swing.JButton btn_DatPhong;
    private javax.swing.JButton btn_DonDatPhong;
    private javax.swing.JButton btn_HoaDon;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logo_holder;
    private javax.swing.JPanel menu_wrapper;
    // End of variables declaration//GEN-END:variables
}
